networks:
  app-network:
    name: wa-network
    driver: bridge

volumes:
  pg_data:
  web_build:

services:
  database:
    image: postgres:latest
    container_name: ${CONTAINER_DB}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 3s

  api:
    build:
      context: ./web-suite-api
      dockerfile: Dockerfile.dev
    container_name: ${CONTAINER_API}
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      PORT: ${API_PORT}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./web-suite-api:/app
      - /app/node_modules
    networks:
      - app-network

  web:
    build:
      context: ./web-suite-webapp
      dockerfile: Dockerfile.prod
    container_name: ${CONTAINER_WEB_APP}
    restart: always
    ports:
      - "${WEB_APP_PORT}:${WEB_APP_PORT}"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
